# **Task 1: What is NumPy?**

# **Research and write a short explanation about NumPy.**

# **Task 2: Why Use NumPy?**

# **Write a few reasons why NumPy is useful.**

# **Task 3: Why is NumPy Faster Than Lists?**

# **Experiment with lists vs. NumPy arrays in performance.**

# **Measure time for list**

# **Measure time for NumPy array**

# **Task 4: Which Language is NumPy written in?**

# **Task 5: Installation of NumPy**

# **Command to install NumPy (run in terminal or command prompt)**

# **Task 6: Dimensions in Arrays**

# **Create arrays of different dimensions**

# **Task 7: Copy and View Functions**

# **Task 8: Join Two Arrays**

# **Task 9: Joining Arrays Using Stack Functions**

# **Task 10: Splitting NumPy Arrays**

# **Task 11: Searching in NumPy Arrays**



# **Desired Output**


In [2]:
Desired_Output="""
Time taken by list: 0.10277843475341797
Time taken by NumPy: 0.009596824645996094
1D Array: [1 2 3]
2D Array: [[1 2 3]
 [4 5 6]]
3D Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Original: [99 20 30]
Copy: [10 20 30]
View: [99 20 30]
Joined Array: [1 2 3 4 5 6]
Stacked Vertically:
 [[1 2 3]
 [4 5 6]]
Stacked Horizontally:
 [1 2 3 4 5 6]
Stacked Depth:
 [[[1 4]
  [2 5]
  [3 6]]]
Split Arrays: [array([1, 2]), array([3, 4]), array([5, 6])]
Index of value 3 in joined_array: (array([2]),) """


print(Desired_Output)



Time taken by list: 0.10277843475341797
Time taken by NumPy: 0.009596824645996094
1D Array: [1 2 3]
2D Array: [[1 2 3]
 [4 5 6]]
3D Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Original: [99 20 30]
Copy: [10 20 30]
View: [99 20 30]
Joined Array: [1 2 3 4 5 6]
Stacked Vertically:
 [[1 2 3]
 [4 5 6]]
Stacked Horizontally:
 [1 2 3 4 5 6]
Stacked Depth:
 [[[1 4]
  [2 5]
  [3 6]]]
Split Arrays: [array([1, 2]), array([3, 4]), array([5, 6])]
Index of value 3 in joined_array: (array([2]),) 


In [1]:
# Question 1
    # What is numpy? Research and write a short explanation about NumPy.
    # Numpy stands for Numerical python, an open source library used for working with arrays it provides mathematical functions for working with arrays, such as linear algebra, numerical computing, and statistical operations It provides efficient multi-dimensional array objects and various mathematical functions for handling large datasets.
    # Numpy arrays are fast, efficient, and essential for data-driven fields. 

In [2]:
# Question 2
    # Why to use numpy array? Write a few reasons why NumPy is useful
    # 1 Fast as compared to lists
    # 2 Less Memory Usage
    # 3 provide Builin Mathematical function
    # 4 Support to handle multi Dimensional Arrays

In [5]:
# Question 3
# Why is NumPy Faster Than Lists? Experiment with lists vs. NumPy arrays in performance
# Measure time for list
# Measure time for NumPy array

# 1. NumPy’s code is written in C and C++, which is faster than Python’s interpreted code.
# 2. Numpy array perform operationsonentire array at once (vectorization)
# 3. it also store data in continuous memory block

import numpy as np
import time

py_list = [i for i in range(1000000)]
t1 = time.time()
new_list = [x + 2 for x in py_list]  
t2 = time.time()

print("Time taken by Python list:", t2 - t1)
print("-----------------------------------")


np_arr = np.arange(1000000)  

t3 = time.time()
new_arr = np_arr + 2  
t4 = time.time()

print("Time taken by NumPy array:", t4 - t3)


Time taken by Python list: 0.15039968490600586
-----------------------------------
Time taken by NumPy array: 0.003996849060058594


In [6]:
# Question 4
#Which Language is NumPy written in 
# NumPy is partially written in C and C++ . The high-level API is written in Python, but all heavy computations are handled by optimized C and C++ code.

In [7]:
# Question 5
# Installation of NumPy Command to install NumPy (run in terminal or command prompt)                                                                                                                                                                                                                                                                                
# **Command to install NumPy (run in terminal or command prompt) 

# pip install numpy

In [8]:
# Question 6
# Dimensions in Arrays**

# 0-D (Zero-Dimensional Array) Scalar
print("-----0D array-----")
arr1=np.array(5)
print(arr1)
print("Dimension: ",arr1.ndim)

# print("Type of array: ",type(arr1))
# print("Size of array: ",arr1.size)
# print("Shape (Rows and columns of array): ",arr1.shape)

print("-----1D array-----")
arr2=np.array([1,0,4,6,3])
print(arr2)
print("Dimension: ",arr2.ndim)
# print("Type of array: ",type(arr2))
# print("Size of array: ",arr2.size)
# print("Shape (Rows and columns of array): ",arr2.shape)

print("-----2D array-----")
arr2=np.array([[1,0,4,6,3],[8,3,6,9,1]])
print(arr2)
print("Dimension: ",arr2.ndim)

print("-----3D array-----")
arr3=np.array([[[1,6,3],[5,9,1]],[[1,0,4],[7,2,1]]])
print(arr3)
print("Dimension: ",arr3.ndim)

print("-----nD array-----")
# arr3=np.array([[[[1,3],[5,1]],[[2,4],[7,0]]]])
# print(arr3)
# print("Dimension: ",arr3.ndim)
arr3=np.array([2,4,6,7],ndmin=7)
print(arr3)
print("Dimension: ",arr3.ndim)





-----0D array-----
5
Dimension:  0
-----1D array-----
[1 0 4 6 3]
Dimension:  1
-----2D array-----
[[1 0 4 6 3]
 [8 3 6 9 1]]
Dimension:  2
-----3D array-----
[[[1 6 3]
  [5 9 1]]

 [[1 0 4]
  [7 2 1]]]
Dimension:  3
-----nD array-----
[[[[[[[2 4 6 7]]]]]]]
Dimension:  7


In [11]:
# Question 7
# Copy and View Functions**
arr1=np.array([2,4,6,8])
new_arr1=arr1.copy()
new_arr1-=1
print("original: ",arr1)
print("Copied  : ",new_arr1)
print()

arr2=np.array([1,2,3,4,5])
new_arr2=arr2.view()
new_arr2*=2
print("original: ",arr2)
print("Viewed  : ",new_arr2)

original:  [2 4 6 8]
Copied  :  [1 3 5 7]

original:  [ 2  4  6  8 10]
Viewed  :  [ 2  4  6  8 10]


In [12]:
# Question 8:
# Join Two Arrays**

arr1=np.array([3,1,0,9])
arr2=np.array([8,5,2,5])
print("Array 1:      ",arr1)
print("Array 2:      ",arr2)
arr3=np.concatenate((arr1,arr2), axis=0)
print("After joining:",arr3)




Array 1:       [3 1 0 9]
Array 2:       [8 5 2 5]
After joining: [3 1 0 9 8 5 2 5]


In [13]:
# Question 9
# Joining Arrays Using Stack Functions
arr1=np.array([4,6,7])
arr2=np.array([1,3,0])

arr=np.stack((arr1,arr2), axis=0)
print(arr)
arr=np.stack((arr1,arr2), axis=1)
print(arr)


arr=np.hstack((arr1,arr2)) # stack dimension of both arrays to horizontal direction
print(arr)
arr=np.vstack((arr1,arr2)) # atack all elements in vertical direction first elemeny of all dimension is stacked to first column
print(arr)
arr=np.dstack((arr1,arr2)) # stack all elements in that are in  corresponding column of both arrays to row
print(arr)


[[4 6 7]
 [1 3 0]]
[[4 1]
 [6 3]
 [7 0]]
[4 6 7 1 3 0]
[[4 6 7]
 [1 3 0]]
[[[4 1]
  [6 3]
  [7 0]]]


In [15]:
# Question 10
# Splitting NumPy Arrays
arr = np.array([1, 2,3, 4, 5,7])

# Split into 3 sub-arrays along rows
result = np.array_split(arr, 3)
print(result)


[array([1, 2]), array([3, 4]), array([5, 7])]


In [ ]:
# Question 11
# Searching in NumPy Arrays
arr=np.array([2,4,6,8,7,9,0,3,5,6,7,8,2])
x= np.where(arr>5)
print(x)