# T**ask 1: What is NumPy?**

# **Research and write a short explanation about NumPy.**

# **Task 2: Why Use NumPy?**

# **Write a few reasons why NumPy is useful.**

# **Task 3: Why is NumPy Faster Than Lists?**

# **Experiment with lists vs. NumPy arrays in performance.**

# **Measure time for list**

# **Measure time for NumPy array**

# **Task 4: Which Language is NumPy written in?**

# **Task 5:                                                                                                                                                                                                                                                                                  
# **Command to install NumPy (run in terminal or command prompt)**

# **Task 6: Dimensions in Arrays**

# **Create arrays of different dimensions**

# **Task 7: Copy and View Functions**

# **Task 8: Join Two Arrays**

# **Task 9: Joining Arrays Using Stack Functions**

# **Task 10: Splitting NumPy Arrays**

# **Task 11: Searching in NumPy Arrays**



# **Desired Output**


In [2]:
Desired_Output="""
Time taken by list: 0.10277843475341797
Time taken by NumPy: 0.009596824645996094
1D Array: [1 2 3]
2D Array: [[1 2 3]
 [4 5 6]]
3D Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Original: [99 20 30]
Copy: [10 20 30]
View: [99 20 30]
Joined Array: [1 2 3 4 5 6]
Stacked Vertically:
 [[1 2 3]
 [4 5 6]]
Stacked Horizontally:
 [1 2 3 4 5 6]
Stacked Depth:
 [[[1 4]
  [2 5]
  [3 6]]]
Split Arrays: [array([1, 2]), array([3, 4]), array([5, 6])]
Index of value 3 in joined_array: (array([2]),) """


print(Desired_Output)



Time taken by list: 0.10277843475341797
Time taken by NumPy: 0.009596824645996094
1D Array: [1 2 3]
2D Array: [[1 2 3]
 [4 5 6]]
3D Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Original: [99 20 30]
Copy: [10 20 30]
View: [99 20 30]
Joined Array: [1 2 3 4 5 6]
Stacked Vertically:
 [[1 2 3]
 [4 5 6]]
Stacked Horizontally:
 [1 2 3 4 5 6]
Stacked Depth:
 [[[1 4]
  [2 5]
  [3 6]]]
Split Arrays: [array([1, 2]), array([3, 4]), array([5, 6])]
Index of value 3 in joined_array: (array([2]),) 


In [ ]:
# Question 1
    # What is numpy? Research and write a short explanation about NumPy.
    # Numpy stands for Numerical python, an open source library used for working with arrays it provides mathematical functions for working with arrays, such as linear algebra, numerical computing, and statistical operations It provides efficient multi-dimensional array objects and various mathematical functions for handling large datasets.
    # Numpu arrays are fast, efficient, and essential for data-driven fields. 

In [ ]:
# Question 2
    # Why to use numpy array? Write a few reasons why NumPy is useful
    # 1 Fast as compared to lists
    # 2 Less Memory Usage
    # 3 provide Builin Mathematical function
    # 4 Support to handle multi Dimensional Arrays

In [ ]:
# Question 3
# Why is NumPy Faster Than Lists? Experiment with lists vs. NumPy arrays in performance
# Measure time for list
# Measure time for NumPy array



In [ ]:
# Question 4
#Which Language is NumPy written in 
# 